//
//  CacheLocationCatalog.swift
//  CacheSweep
//

import Foundation

enum CacheLocationCatalog {
    private static let homeDirectory = FileManager.default.homeDirectoryForCurrentUser.path()

    static let builtInLocations: [CacheLocation] = [
        CacheLocation(
            path: "\(homeDirectory)/Library/Containers/com.apple.CoreDevice.CoreDeviceService/Data/Library/Caches/AppInstallationBinaryDeltas",
            name: "Core Device Service",
            description: "Cached app installation deltas and related device support data used by CoreDevice during development workflows.",
            isCritical: false,
            isCustom: false
        ),
        CacheLocation(
            path: "\(homeDirectory)/Library/Developer/Xcode/DerivedData",
            name: "Xcode DerivedData",
            description: "Build products, indexes, and intermediate files generated by Xcode. Safe to remove, but projects will rebuild afterward.",
            isCritical: false,
            isCustom: false
        ),
        CacheLocation(
            path: "\(homeDirectory)/Library/Developer/CoreSimulator/Caches",
            name: "Simulator Caches",
            description: "Cached data created by iOS and watchOS simulators. Mainly useful on development machines.",
            isCritical: false,
            isCustom: false
        ),
        CacheLocation(
            path: "\(homeDirectory)/Library/Containers/com.apple.wallpaper.agent/Data/Library/Caches",
            name: "Wallpaper Agent",
            description: "Wallpaper image cache used by macOS wallpaper services.",
            isCritical: false,
            isCustom: false
        ),
        CacheLocation(
            path: "\(homeDirectory)/Library/Caches",
            name: "User Caches",
            description: "General cache directory for apps and agents in the current user account.",
            isCritical: false,
            isCustom: false
        ),
        CacheLocation(
            path: "/Library/Caches",
            name: "System Caches",
            description: "Global cache directory used by system daemons and applications.",
            isCritical: false,
            isCustom: false
        ),
        CacheLocation(
            path: "/Library/HTTPStorages",
            name: "HTTP Storages",
            description: "Shared URL loading storage used by some apps and services for cached HTTP responses and session data.",
            isCritical: false,
            isCustom: false
        ),
        CacheLocation(
            path: "/Library/Application Support/com.apple.idleassetsd",
            name: "Idle Assets",
            description: "Downloaded background assets managed by macOS for preloading and system content updates.",
            isCritical: false,
            isCustom: false
        ),
        CacheLocation(
            path: "/Library/Logs",
            name: "System Logs",
            description: "System-wide log files for apps and services. Clearing them removes diagnostic history, not just cache data.",
            isCritical: true,
            isCustom: false
        ),
        CacheLocation(
            path: "/private/var/log",
            name: "Core System Logs",
            description: "Primary low-level system log directory containing daemon, install, and diagnostic logs.",
            isCritical: true,
            isCustom: false
        ),
        CacheLocation(
            path: "/private/var/db/diagnostics",
            name: "Diagnostics Reports",
            description: "Crash, hang, and diagnostic reports collected by macOS for troubleshooting.",
            isCritical: true,
            isCustom: false
        ),
        CacheLocation(
            path: "/private/var/db/powerlog",
            name: "Power Logs",
            description: "Power and battery telemetry logs used for diagnostics and energy analysis.",
            isCritical: false,
            isCustom: false
        ),
        CacheLocation(
            path: "/private/var/tmp",
            name: "Temporary Files",
            description: "Temporary storage used by system and apps; cleared periodically.",
            isCritical: false,
            isCustom: false
        ),
    ]
}
